apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lms-network-policy
  namespace: library-system
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow all within namespace
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: library-system
    # Allow ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
  egress:
    # Allow all within namespace
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: library-system
    # Allow DNS
    - to: []
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-policy
  namespace: library-system
spec:
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
    - Ingress
  ingress:
    # Only backend services can reach postgres
    - from:
        - podSelector:
            matchLabels:
              app: book-service
        - podSelector:
            matchLabels:
              app: member-service
        - podSelector:
            matchLabels:
              app: lending-service
      ports:
        - port: 5432
