apiVersion: v1
kind: Secret
metadata:
  name: lms-secrets
  namespace: library-system
type: Opaque
stringData:
  POSTGRES_USER: library
  POSTGRES_PASSWORD: library_secure_password_change_in_prod
  DATABASE_URL: postgresql+asyncpg://library:library_secure_password_change_in_prod@postgres:5432/librarydb
