# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import book_pb2 as book__pb2
import common_pb2 as common__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in book_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBook = channel.unary_unary(
                '/book.BookService/CreateBook',
                request_serializer=book__pb2.CreateBookRequest.SerializeToString,
                response_deserializer=book__pb2.Book.FromString,
                _registered_method=True)
        self.UpdateBook = channel.unary_unary(
                '/book.BookService/UpdateBook',
                request_serializer=book__pb2.UpdateBookRequest.SerializeToString,
                response_deserializer=book__pb2.Book.FromString,
                _registered_method=True)
        self.GetBook = channel.unary_unary(
                '/book.BookService/GetBook',
                request_serializer=book__pb2.GetBookRequest.SerializeToString,
                response_deserializer=book__pb2.Book.FromString,
                _registered_method=True)
        self.ListBooks = channel.unary_unary(
                '/book.BookService/ListBooks',
                request_serializer=book__pb2.ListBooksRequest.SerializeToString,
                response_deserializer=book__pb2.ListBooksResponse.FromString,
                _registered_method=True)
        self.SearchBooks = channel.unary_unary(
                '/book.BookService/SearchBooks',
                request_serializer=book__pb2.SearchBooksRequest.SerializeToString,
                response_deserializer=book__pb2.SearchBooksResponse.FromString,
                _registered_method=True)
        self.CheckAvailability = channel.unary_unary(
                '/book.BookService/CheckAvailability',
                request_serializer=book__pb2.CheckAvailabilityRequest.SerializeToString,
                response_deserializer=book__pb2.CheckAvailabilityResponse.FromString,
                _registered_method=True)
        self.DecreaseAvailableCopies = channel.unary_unary(
                '/book.BookService/DecreaseAvailableCopies',
                request_serializer=book__pb2.UpdateCopiesRequest.SerializeToString,
                response_deserializer=book__pb2.UpdateCopiesResponse.FromString,
                _registered_method=True)
        self.IncreaseAvailableCopies = channel.unary_unary(
                '/book.BookService/IncreaseAvailableCopies',
                request_serializer=book__pb2.UpdateCopiesRequest.SerializeToString,
                response_deserializer=book__pb2.UpdateCopiesResponse.FromString,
                _registered_method=True)
        self.DeleteBook = channel.unary_unary(
                '/book.BookService/DeleteBook',
                request_serializer=book__pb2.DeleteBookRequest.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)


class BookServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecreaseAvailableCopies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncreaseAvailableCopies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBook,
                    request_deserializer=book__pb2.CreateBookRequest.FromString,
                    response_serializer=book__pb2.Book.SerializeToString,
            ),
            'UpdateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBook,
                    request_deserializer=book__pb2.UpdateBookRequest.FromString,
                    response_serializer=book__pb2.Book.SerializeToString,
            ),
            'GetBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBook,
                    request_deserializer=book__pb2.GetBookRequest.FromString,
                    response_serializer=book__pb2.Book.SerializeToString,
            ),
            'ListBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBooks,
                    request_deserializer=book__pb2.ListBooksRequest.FromString,
                    response_serializer=book__pb2.ListBooksResponse.SerializeToString,
            ),
            'SearchBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchBooks,
                    request_deserializer=book__pb2.SearchBooksRequest.FromString,
                    response_serializer=book__pb2.SearchBooksResponse.SerializeToString,
            ),
            'CheckAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAvailability,
                    request_deserializer=book__pb2.CheckAvailabilityRequest.FromString,
                    response_serializer=book__pb2.CheckAvailabilityResponse.SerializeToString,
            ),
            'DecreaseAvailableCopies': grpc.unary_unary_rpc_method_handler(
                    servicer.DecreaseAvailableCopies,
                    request_deserializer=book__pb2.UpdateCopiesRequest.FromString,
                    response_serializer=book__pb2.UpdateCopiesResponse.SerializeToString,
            ),
            'IncreaseAvailableCopies': grpc.unary_unary_rpc_method_handler(
                    servicer.IncreaseAvailableCopies,
                    request_deserializer=book__pb2.UpdateCopiesRequest.FromString,
                    response_serializer=book__pb2.UpdateCopiesResponse.SerializeToString,
            ),
            'DeleteBook': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBook,
                    request_deserializer=book__pb2.DeleteBookRequest.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'book.BookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('book.BookService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/book.BookService/CreateBook',
            book__pb2.CreateBookRequest.SerializeToString,
            book__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/book.BookService/UpdateBook',
            book__pb2.UpdateBookRequest.SerializeToString,
            book__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/book.BookService/GetBook',
            book__pb2.GetBookRequest.SerializeToString,
            book__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/book.BookService/ListBooks',
            book__pb2.ListBooksRequest.SerializeToString,
            book__pb2.ListBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/book.BookService/SearchBooks',
            book__pb2.SearchBooksRequest.SerializeToString,
            book__pb2.SearchBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/book.BookService/CheckAvailability',
            book__pb2.CheckAvailabilityRequest.SerializeToString,
            book__pb2.CheckAvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecreaseAvailableCopies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/book.BookService/DecreaseAvailableCopies',
            book__pb2.UpdateCopiesRequest.SerializeToString,
            book__pb2.UpdateCopiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IncreaseAvailableCopies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/book.BookService/IncreaseAvailableCopies',
            book__pb2.UpdateCopiesRequest.SerializeToString,
            book__pb2.UpdateCopiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/book.BookService/DeleteBook',
            book__pb2.DeleteBookRequest.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
