# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import member_pb2 as member__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in member_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemberServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMember = channel.unary_unary(
                '/member.MemberService/CreateMember',
                request_serializer=member__pb2.CreateMemberRequest.SerializeToString,
                response_deserializer=member__pb2.Member.FromString,
                _registered_method=True)
        self.UpdateMember = channel.unary_unary(
                '/member.MemberService/UpdateMember',
                request_serializer=member__pb2.UpdateMemberRequest.SerializeToString,
                response_deserializer=member__pb2.Member.FromString,
                _registered_method=True)
        self.GetMember = channel.unary_unary(
                '/member.MemberService/GetMember',
                request_serializer=member__pb2.GetMemberRequest.SerializeToString,
                response_deserializer=member__pb2.Member.FromString,
                _registered_method=True)
        self.ListMembers = channel.unary_unary(
                '/member.MemberService/ListMembers',
                request_serializer=member__pb2.ListMembersRequest.SerializeToString,
                response_deserializer=member__pb2.ListMembersResponse.FromString,
                _registered_method=True)
        self.ValidateActiveMember = channel.unary_unary(
                '/member.MemberService/ValidateActiveMember',
                request_serializer=member__pb2.ValidateActiveMemberRequest.SerializeToString,
                response_deserializer=member__pb2.ValidateActiveMemberResponse.FromString,
                _registered_method=True)
        self.DeactivateMember = channel.unary_unary(
                '/member.MemberService/DeactivateMember',
                request_serializer=member__pb2.DeactivateMemberRequest.SerializeToString,
                response_deserializer=member__pb2.Member.FromString,
                _registered_method=True)


class MemberServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateActiveMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeactivateMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemberServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMember,
                    request_deserializer=member__pb2.CreateMemberRequest.FromString,
                    response_serializer=member__pb2.Member.SerializeToString,
            ),
            'UpdateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMember,
                    request_deserializer=member__pb2.UpdateMemberRequest.FromString,
                    response_serializer=member__pb2.Member.SerializeToString,
            ),
            'GetMember': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMember,
                    request_deserializer=member__pb2.GetMemberRequest.FromString,
                    response_serializer=member__pb2.Member.SerializeToString,
            ),
            'ListMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMembers,
                    request_deserializer=member__pb2.ListMembersRequest.FromString,
                    response_serializer=member__pb2.ListMembersResponse.SerializeToString,
            ),
            'ValidateActiveMember': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateActiveMember,
                    request_deserializer=member__pb2.ValidateActiveMemberRequest.FromString,
                    response_serializer=member__pb2.ValidateActiveMemberResponse.SerializeToString,
            ),
            'DeactivateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.DeactivateMember,
                    request_deserializer=member__pb2.DeactivateMemberRequest.FromString,
                    response_serializer=member__pb2.Member.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'member.MemberService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('member.MemberService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemberService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/member.MemberService/CreateMember',
            member__pb2.CreateMemberRequest.SerializeToString,
            member__pb2.Member.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/member.MemberService/UpdateMember',
            member__pb2.UpdateMemberRequest.SerializeToString,
            member__pb2.Member.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/member.MemberService/GetMember',
            member__pb2.GetMemberRequest.SerializeToString,
            member__pb2.Member.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/member.MemberService/ListMembers',
            member__pb2.ListMembersRequest.SerializeToString,
            member__pb2.ListMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateActiveMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/member.MemberService/ValidateActiveMember',
            member__pb2.ValidateActiveMemberRequest.SerializeToString,
            member__pb2.ValidateActiveMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeactivateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/member.MemberService/DeactivateMember',
            member__pb2.DeactivateMemberRequest.SerializeToString,
            member__pb2.Member.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
