# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import lending_pb2 as lending__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in lending_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LendingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BorrowBook = channel.unary_unary(
                '/lending.LendingService/BorrowBook',
                request_serializer=lending__pb2.BorrowBookRequest.SerializeToString,
                response_deserializer=lending__pb2.LendingRecord.FromString,
                _registered_method=True)
        self.ReturnBook = channel.unary_unary(
                '/lending.LendingService/ReturnBook',
                request_serializer=lending__pb2.ReturnBookRequest.SerializeToString,
                response_deserializer=lending__pb2.ReturnBookResponse.FromString,
                _registered_method=True)
        self.ListBorrowedBooks = channel.unary_unary(
                '/lending.LendingService/ListBorrowedBooks',
                request_serializer=lending__pb2.ListBorrowedBooksRequest.SerializeToString,
                response_deserializer=lending__pb2.ListBorrowedBooksResponse.FromString,
                _registered_method=True)
        self.ListBorrowedBooksByMember = channel.unary_unary(
                '/lending.LendingService/ListBorrowedBooksByMember',
                request_serializer=lending__pb2.ListBorrowedBooksByMemberRequest.SerializeToString,
                response_deserializer=lending__pb2.ListBorrowedBooksResponse.FromString,
                _registered_method=True)
        self.ListBookBorrowHistory = channel.unary_unary(
                '/lending.LendingService/ListBookBorrowHistory',
                request_serializer=lending__pb2.ListBookBorrowHistoryRequest.SerializeToString,
                response_deserializer=lending__pb2.ListBorrowedBooksResponse.FromString,
                _registered_method=True)
        self.ListOverdueBooks = channel.unary_unary(
                '/lending.LendingService/ListOverdueBooks',
                request_serializer=lending__pb2.ListOverdueBooksRequest.SerializeToString,
                response_deserializer=lending__pb2.ListBorrowedBooksResponse.FromString,
                _registered_method=True)


class LendingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BorrowBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBorrowedBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBorrowedBooksByMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBookBorrowHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOverdueBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LendingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BorrowBook': grpc.unary_unary_rpc_method_handler(
                    servicer.BorrowBook,
                    request_deserializer=lending__pb2.BorrowBookRequest.FromString,
                    response_serializer=lending__pb2.LendingRecord.SerializeToString,
            ),
            'ReturnBook': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnBook,
                    request_deserializer=lending__pb2.ReturnBookRequest.FromString,
                    response_serializer=lending__pb2.ReturnBookResponse.SerializeToString,
            ),
            'ListBorrowedBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBorrowedBooks,
                    request_deserializer=lending__pb2.ListBorrowedBooksRequest.FromString,
                    response_serializer=lending__pb2.ListBorrowedBooksResponse.SerializeToString,
            ),
            'ListBorrowedBooksByMember': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBorrowedBooksByMember,
                    request_deserializer=lending__pb2.ListBorrowedBooksByMemberRequest.FromString,
                    response_serializer=lending__pb2.ListBorrowedBooksResponse.SerializeToString,
            ),
            'ListBookBorrowHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBookBorrowHistory,
                    request_deserializer=lending__pb2.ListBookBorrowHistoryRequest.FromString,
                    response_serializer=lending__pb2.ListBorrowedBooksResponse.SerializeToString,
            ),
            'ListOverdueBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOverdueBooks,
                    request_deserializer=lending__pb2.ListOverdueBooksRequest.FromString,
                    response_serializer=lending__pb2.ListBorrowedBooksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lending.LendingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lending.LendingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LendingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BorrowBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lending.LendingService/BorrowBook',
            lending__pb2.BorrowBookRequest.SerializeToString,
            lending__pb2.LendingRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lending.LendingService/ReturnBook',
            lending__pb2.ReturnBookRequest.SerializeToString,
            lending__pb2.ReturnBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBorrowedBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lending.LendingService/ListBorrowedBooks',
            lending__pb2.ListBorrowedBooksRequest.SerializeToString,
            lending__pb2.ListBorrowedBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBorrowedBooksByMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lending.LendingService/ListBorrowedBooksByMember',
            lending__pb2.ListBorrowedBooksByMemberRequest.SerializeToString,
            lending__pb2.ListBorrowedBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBookBorrowHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lending.LendingService/ListBookBorrowHistory',
            lending__pb2.ListBookBorrowHistoryRequest.SerializeToString,
            lending__pb2.ListBorrowedBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOverdueBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lending.LendingService/ListOverdueBooks',
            lending__pb2.ListOverdueBooksRequest.SerializeToString,
            lending__pb2.ListBorrowedBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
